### ISSUE TITLE
add small description about the programs

### ISSUE THREAD

**Issue by addy1997** [addy1997/al-Go-rithms#15]
Hi @rootVIII,

Could you please add a small description to all three programs submitted?  Single `comment` atop the file will do. 

1. len_last_word
2. remove_in_place
3. plus_one

Thanks

**Comment by rootVIII** [comment]
Sure will do... sorry about that

**Comment by addy1997** [comment]
No worries

**Comment by rootVIII** [comment]
Hmm I can't seem to open a new branch on the repository?

**Comment by addy1997** [comment]
> Hmm I can't seem to open a new branch on the repository?

have you `fetched the origin`?

**Comment by rootVIII** [comment]
Usually I will create a feature branch off of master (or main or Develop) and push to this branch. But looking in your repository, there is no option to "find or create branch..." in the repository anymore? It was there when I first pushed the code (in the dropdown under the 'main' button.

**Comment by addy1997** [comment]
> Usually I will create a feature branch off of master (or main or Develop) and push to this branch. But looking in your repository, there is no option to "find or create branch..." in the repository anymore? It was there when I first pushed the code (in the dropdown under the 'main' button.

This is strange. Anyways, I will do it for you.

**Comment by rootVIII** [comment]
I think I may need to be added as collaborator?
Here is exact issue: https://stackoverflow.com/questions/30948978/cannot-create-branch-in-github

my bad! Invitation sent. I am sorry
