### ISSUE TITLE
Space in folder name "Dynamic Programming"

### ISSUE THREAD

**Issue by Abby3017** [addy1997/al-Go-rithms#16]
If you keep space in Folder name, while running test case This error is showing:

> import path contains space character:

So naming like this throws error and is against the convention of Go.
We can name this folder as "dynamicProgramming", one of my suggestion. You can read more about it here https://blog.golang.org/package-names

**Comment by addy1997** [comment]
@Abby3017, thanks for identifying this. So, you mean we should write it in `smallCamel` case? Something link [this](https://betterprogramming.pub/naming-conventions-in-go-short-but-descriptive-1fa7c6d2f32a?gi=baec5023d9d8). I have made the changes, please check it.
