### ISSUE TITLE
fix the array allocation in the tiling program

### ISSUE THREAD

**Issue by addy1997** [addy1997/al-Go-rithms#8]
error is 

./main.go:38:17: cannot use F (type [2][2]uint) as type [][2]uint in argument to Multiply
./main.go:65:15: cannot use c (type [2][2]uint) as type [][2]uint in argument to Power

**Comment by Abby3017** [comment]
Can you provide more detail about this issue ?
I can take a look into this

**Comment by addy1997** [comment]
> Can you provide more detail about this issue?
> I can take a look into this

Well, the problem is with the size of the 2d array ((type [2][2]uint)). What I mean is that, since `golang` is statically typed, you can't change the size allocated in the beginning.

**Comment by Abby3017** [comment]
Hey, is this problem is based on this tiling problem
Given a floor of size n x 2 and tiles of size 1 x 2. The problem is to count the number of ways to tile the given floor using 1 x 2 tiles. A tile can either be placed horizontally or vertically. 
If not can you share the problem statement.

**Comment by addy1997** [comment]
> Hey, is this problem is based on this tiling problem
> Given a floor of size n x 2 and tiles of size 1 x 2. The problem is to count the number of ways to tile the given floor using 1 x 2 tiles. A tile can either be placed horizontally or vertically.
> If not can you share the problem statement.

Well, I wrote the program referring this [article](https://www.geeksforgeeks.org/tiling-problem/). It might give you some idea. 

Also, the error is
```

Printf format %1l has unknown verb l
unreachable code

```

Lines that give this error

```
fmt.Scanf("%1lu",&n)
fmt.Printf("%1lu\n",c[0][0])

```

**Comment by Abby3017** [comment]
Then this can be implemented more easily and other thing is in Power function return statement is used inside if condition which makes other code unreachable. So I was not getting why it was written like that 
Should I re write the whole problem based on given article as it is based on Fibonacci series for solution.

For your issue `%1lu` this verb is not present in Printf.
You can check the list here https://golang.org/pkg/fmt/#:~:text=The%20Printf%20verbs%20%25p%20and,%2B7%22%2C%20%220x4.
Thats why that error is showing

**Comment by addy1997** [comment]
> Then this can be implemented more easily and other thing is in Power function return statement is used inside if condition which makes other code unreachable. So I was not getting why it was written like that
> Should I re write the whole problem based on given article as it is based on Fibonacci series for solution.

Yes, please go ahead. It will be great if you could rewrite it.

**Comment by addy1997** [comment]
@Abby3017 great job, thanks for fixing the issue. I am closing this issue now.
